# Цей файл явно вказує Netlify, де шукати ваші серверні функції.
[build]
  functions = "netlify/functions/"

# Це правило перенаправляє ТІЛЬКИ конкретний запит /api/generate-image
# на ТІЛЬКИ конкретну функцію /.netlify/functions/generate-image.
# Це найбільш надійний спосіб.
[[redirects]]
  from = "/api/generate-image"
  to = "/.netlify/functions/generate-image"
  status = 200
  force = true

